### ISSUE TITLE
Can only run 1 server

### ISSUE THREAD

**Issue by Sutwick** [deafdudecomputers/PalWorldServer#2]
If you try to run more than 1 instance the first will be closed when you run the second.. Even though they have there own ports and own file DIR.

**Comment by deafdudecomputers** [comment]
Seems to occur if the server_launcher_xbox.py is being used for each instance of server. The solution is to rename that file to something like server_launcher_xbox1.py, and name other one as server_launcher_xbox2.py. Then update the .cmd to reflect on new named file to execute. 

Apologizes for this.
